title: "Stefan Maric"
tagline: "Web Developer"
description: "Web Developer, MongoDB Certified Professional℠, and Squirrel Lover"
logo: /img/logo.png

author:
  name: Stefan Maric
  url: http://stefanmaric.com
  email: me@stefanmaric.com

facebook:
  username: StefanAlexanderMaric
github:
  username: stefanmaric
google:
  username: +StefanAlexanderMaric
linkedin:
  username: maricstefan
skype:
  username: alexstefan922
twitter:
  username: stefanmaric_

social:
  name: Stefan Maric
  links:
    - https://twitter.com/stefanmaric_
    - https://www.facebook.com/StefanAlexanderMaric
    - https://linkedin.com/in/maricstefan/en
    - https://plus.google.com/+StefanAlexanderMaric
    - https://github.com/stefanmaric

markdown: kramdown
plugins:
  - jekyll-seo-tag
