# Site settings
title: "Stefan Maric"
tagline: "Web Developer"
description: "Web Developer, MongoDB Certified Professional℠, and Squirrel Lover"

email: me@stefanmaric.com
twitter_username: stefanmaric_
github_username: stefanmaric
facebook_username: StefanAlexanderMaric
skype_username: alexstefan922
google_username: +StefanAlexanderMaric
linkedin_url: http://ve.linkedin.com/in/maricstefan/en

author:
  name: Stefan Maric
  url: http://stefanmaric.com
  email: me@stefanmaric.com

markdown: kramdown
plugins:
  - jekyll-seo-tag
