# Site settings
title: "Stefan Alexander Maric - Web Developer, MongoDB Certified Professional℠, and Squirrel Lover"
tagline: Web Developer
description: "Stefan Maric - Web Developer, MongoDBA, and Squirrel Lover"
baseurl: ""
url: "http://stefanmaric.com"
email: me@stefanmaric.com
twitter_username: stefanmaric_
github_username: stefanmaric
facebook_username: StefanAlexanderMaric
skype_username: alexstefan922
google_username: +StefanAlexanderMaric
linkedin_url: http://ve.linkedin.com/in/maricstefan/en
author:
  name: Stefan Maric
  url: http://stefanmaric.com
  email: me@stefanmaric.com
github:
  repo: https://github.com/stefanmaric/stefanmaric.github.io

# Build settings
exclude: ["node_modules","components"]
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-seo-tag
